# Site settings
title: Prof. Xiaohua Jia's Lab
email:
description: Prof. Xiaohua Jia's Lab is in the Department of Computer Science at City University of Hong Kong, focusing on data privacy, blockchain, distributed systems, networking, cloud computing, and mobile computing research.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

sass:
    sass_dir: styles/_sass
    style: compressed
